# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
