# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181128_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isdeleted',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.NullBooleanField(default=True),
        ),
    ]
