# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20181128_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_selected',
            field=models.IntegerField(default=0),
        ),
    ]
